# Generated by Django 3.0.4 on 2020-06-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminusers',
            name='password1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
