# Generated by Django 3.0.4 on 2020-06-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminusers_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusers',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminusers',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminusers',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
