# Generated by Django 3.0.4 on 2020-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200612_0602'),
        ('customer', '0004_auto_20200612_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ManyToManyField(to='users.adminUsers'),
        ),
    ]
