# Generated by Django 3.0.4 on 2020-06-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200612_0602'),
        ('customer', '0006_auto_20200612_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminUsers'),
        ),
    ]
